### ISSUE TITLE
Can't download Nota app

### ISSUE THREAD

**Issue by Lucas-nac27** [pouyakary/Nota#4]
I can't download the app because the website at http://codes.kary.us/nota/nota.git was not found.

**Comment by pouyakary** [comment]
Hey @Lucas-nac27, yeah you can use this repos instead. But I'm working on a much new version that is way better and more interesting. So this version is somehow deprecated. If you wish to you can clone the repo and run `make install` on it

**Comment by pouyakary** [comment]
Also I updated the repo and its install.sh file. So you can do use the new version now
